### PR TITLE
Add /.cache/ to gitignore (tooling section)

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Update `.gitignore` to not pick up on newer directories of `clangd`

ENDRELEASENOTES

### CODE REVIEW

**Comment by jmcarcell** [comment]
I have nothing against this but I think we should have this be managed at once for all the key4hep repos instead of adding it one by one, let me see if I can have a look today

**Comment by tmadlener** [comment]
If that would be possible I would very much prefer that

**Comment by andresailer** [comment]
@tmadlener: Are you making use of the global git-ignore? https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

**Comment by tmadlener** [comment]
Not yet actually. I should probably. Maybe we could also provide a sort of default one for Key4hep as a starting point for people?

**Comment by jmcarcell** [comment]
Yes, first we should agree on a default one and then I have a tool I can adapt to push the changes to most of the repos. See https://github.com/key4hep/key4hep-dev-utils/pull/1 for an example

**Comment by jmcarcell** [comment]
After https://github.com/key4hep/key4hep-dev-utils/pull/1 a default `.gitignore` was added and pushed to EDM4hep among others so this is no longer relevant unless there are more paths to add

**Pull request closed without merging**
