### PR TITLE
[delphes] convert particle status

### PR DESCRIPTION
**Pull request by vvolkl**
BEGINRELEASENOTES
- save the delphes particle status as edm4hep::MCparticle.GeneratorStatus

ENDRELEASENOTES

### CODE REVIEW

**Comment by tmadlener** [comment]
This looks good to me. Should we add a link to delphes to the README in order to make it easier on how to interpret this value? (Or is that "common knowledge"?)

**Comment by clementhelsens** [comment]
> This looks good to me. Should we add a link to delphes to the README in order to make it easier on how to interpret this value? (Or is that "common knowledge"?)

It does not comes from Delphes only.
For example if you run pythia, you will have statuses according to what pythia8 does:
http://home.thep.lu.se/~torbjorn/pythia81html/ParticleProperties.html

**Comment by tmadlener** [comment]
Ah, I see. I am not sure if I understand the Delphes documentation on the `Candidate::Status`. Is it only filled from the generator/input and not changed by Delphes after that? That is what I understand, but I am not entirely sure whether that is actually the case. But if it is the case, than we could simply say that we use the same value that the generator provides.

Or maybe even less specific: We just use what Delphes gives us and it is than users that know how to use it with Delphes output would also know how to use it in the edm4hep case?

**Comment by vvolkl** [comment]
In the case of DelphesPythia8, the status of the candidate is set like this: https://github.com/key4hep/EDM4hep/blob/master/plugins/delphes/DelphesPythia8Reader.h#L92
I'm not sure if the `Status` of DelphesCandidate is used otherwise, but for this usecase this seems like the right thing.

**Comment by vvolkl** [comment]
CI failing because I cleaned up the setup scripts on cvmfs - now points to the one that is also mentioned in the docs.

**Comment by tmadlener** [comment]
> In the case of DelphesPythia8, the status of the candidate is set like this: https://github.com/key4hep/EDM4hep/blob/master/plugins/delphes/DelphesPythia8Reader.h#L92
> I'm not sure if the `Status` of DelphesCandidate is used otherwise, but for this usecase this seems like the right thing.

Yes, I agree.

**Review by tmadlener — APPROVED** [review]
Is the CI still broken, or are we just seeing an old status?

**Pull request merged**
