### PR TITLE
Remove `radiusOfInnermostHit` from tracks

### PR DESCRIPTION
**Pull request by jmcarcell**
as discussed in https://github.com/key4hep/EDM4hep/issues/319. 

Changes in other repos:
- https://github.com/key4hep/k4FWCore/pull/202
- https://github.com/key4hep/k4SimDelphes/pull/119
- https://github.com/key4hep/k4EDM4hep2LcioConv/pull/72

BEGINRELEASENOTES
- Remove `radiusOfInnermostHit` from tracks

ENDRELEASENOTES

### CODE REVIEW

**Comment by tmadlener** [comment]
The fact that this requires changes in `k4SimDelphes` makes me think this will also show up in some analyses in FCCAnalyses, but I haven't checked.

**Comment by jmcarcell** [comment]
I checked and didn't find anything in FCCAnalyses

**Comment by tmadlener** [comment]
OK. Then maybe it was there only temporarily, or we just filled it in k4SimDelphes because we could. Thanks for checking.

**Review by hegner — APPROVED** [review]

**Comment by hegner** [comment]
Perfect. Good we checked this again :)

**Comment by hegner** [comment]
can we maybe finally fix the release build test environment? Otherwise I am fine with merging

**Comment by tmadlener** [comment]
Fixing the release build would require a new Key4hep release. For EDM4hep we could in principle pick up the latest podio tag, but for other packages, we would also need a new EDM4hep tag. I am not sure if we want to make such a tag at the moment.

**Pull request merged**
